### ISSUE TITLE
[Bug] PineconeArgumentError: The argument to upsert had type errors: argument must be array.

### ISSUE THREAD

**Issue by PrimeObjects** [pinecone-io/pinecone-ts-client#103]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

No matter upsert or deleteMany, I alway got the error below.

error: PineconeArgumentError: The argument to upsert had type errors: argument must be array.
      at UpsertCommand.validator (D:\EncodeChat\encodechat-lambda\encodechat-lambda-vectordb\node_modules\@pinecone-database\pinecone\src\validator.ts:253:13)
      at UpsertCommand.<anonymous> (D:\EncodeChat\encodechat-lambda\encodechat-lambda-vectordb\node_modules\@pinecone-database\pinecone\src\data\upsert.ts:23:10)
      at step (D:\EncodeChat\encodechat-lambda\encodechat-lambda-vectordb\node_modules\@pinecone-database\pinecone\dist\data\upsert.js:33:23)  
      at Object.next (D:\EncodeChat\encodechat-lambda\encodechat-lambda-vectordb\node_modules\@pinecone-database\pinecone\dist\data\upsert.js:14:53)
      at D:\EncodeChat\encodechat-lambda\encodechat-lambda-vectordb\node_modules\@pinecone-database\pinecone\dist\data\upsert.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (D:\EncodeChat\encodechat-lambda\encodechat-lambda-vectordb\node_modules\@pinecone-database\pinecone\dist\data\upsert.js:4:12)
      at UpsertCommand.UpsertCommand.run (D:\EncodeChat\encodechat-lambda\encodechat-lambda-vectordb\node_modules\@pinecone-database\pinecone\src\data\upsert.ts:22:46)
      at Index.<anonymous> (D:\EncodeChat\encodechat-lambda\encodechat-lambda-vectordb\node_modules\@pinecone-database\pinecone\src\data\index.ts:89:38)
      at step (D:\EncodeChat\encodechat-lambda\encodechat-lambda-vectordb\node_modules\@pinecone-database\pinecone\dist\data\index.js:33:23)   
      at Object.next (D:\EncodeChat\encodechat-lambda\encodechat-lambda-vectordb\node_modules\@pinecone-database\pinecone\dist\data\index.js:14:53)
      at D:\EncodeChat\encodechat-lambda\encodechat-lambda-vectordb\node_modules\@pinecone-database\pinecone\dist\data\index.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (D:\EncodeChat\encodechat-lambda\encodechat-lambda-vectordb\node_modules\@pinecone-database\pinecone\dist\data\index.js:4:12)
      at Index.Index.upsert (D:\EncodeChat\encodechat-lambda\encodechat-lambda-vectordb\node_modules\@pinecone-database\pinecone\src\data\index.ts:88:46)
      at <anonymous> (D:\EncodeChat\encodechat-lambda\encodechat-lambda-vectordb\src\util\process.ts:277:47)
}

### Expected Behavior

upsert or deleteMany successfully.

### Steps To Reproduce

const metadata: TPineconeMetadata = {
            entityName,
            entityType,
            recordId: id,
            ownerIds: [id],
            organizationId,
            solutionId,
            userId,
            text
        };
        
        const pinecone = new Pinecone({
                apiKey,
                environment
            });

        pinecone.index<TPineconeMetadata>(indexName)

        await index.namespace(organizationId).upsert({
            id: "1234",
            values,
            metadata
        });

### Environment

```markdown
- **OS**:
- **Language version**:
- **Pinecone client version**:
```

**Comment by jhamon** [comment]
I think your filter expression is invalid. You can see some docs about filter expressions [here](https://docs.pinecone.io/docs/metadata-filtering).

I think what you need to write is along these lines:

```ts
await index.namespace(organizationId).deleteMany({
  recordId: {
    $eq: '2bb22982-40d4-4156-a1d7-fcf11610e5c3'
  },
});
```

It's on my todo list to add better typing around these filter expressions.

**Comment by bcldvd** [comment]
I'm having the same error with an upsert:
```js
await index.upsert({ 
        upsertRequest: 
          { 
            vectors
          }
       })
    }
```

with `vectors` object looking like this:
```
[
  {
    id: "super-nice-id",
    values: [
      -0.026263636,
      ....
    ],
    metadata: {},
  },
]
```

**Comment by ElliotVilhelm** [comment]
> I think your filter expression is invalid. You can see some docs about filter expressions [here](https://docs.pinecone.io/docs/metadata-filtering).
> 
> I think what you need to write is along these lines, without the top-level `filter`:
> 
> ```ts
> await index.namespace(organizationId).deleteMany({
>   recordId: '2bb22982-40d4-4156-a1d7-fcf11610e5c3'
> });
> ```
> 
> It's on my todo list to add better typing around these filter expressions.

Thanks, that was my issue.

**Comment by jhamon** [comment]
Glad that unblocked you.

I have some promising work-in-progress on adding type-safety to these filter expressions, but I've paused it to prioritize showstopper bugs (e.g. typescript compilation problems) for the next incremental release. Hopefully I'll get that type safety improvement out sometime in the next couple weeks.

**Comment by MontoyaAndres** [comment]
Yes, I just updated to the new 1 version, and I got this error:

illegal condition for field filter, got {"knowledgeId":{"$eq":"xxx"},"type":{"$eq":"xxx"},"workspaceId":{"$eq":"xxx"}}

And we just had to remove the filter: {xxx} object

Also, the documentation is not updated with these changes, it's still using the old methodology https://docs.pinecone.io/docs/metadata-filtering#deleting-vectors-by-metadata-filter

![image](https://github.com/pinecone-io/pinecone-ts-client/assets/15065852/fc50f276-23b5-4449-bd44-54f14f64884a)
