### ISSUE TITLE
Tests fail.

### ISSUE THREAD

**Issue by sammyjava** [pinecone-io/pinecone-ts-client#26]
I've not been able to query an index without receiving a 401 in my app, so I cloned the repo and ran `npm run test`. They fail. This does not seem like an optimal situation. (In my app, I can initialize the client and get an index, but all index operations like query and fetch return 401s.) I have made sure that the test app has my API key and environment.

```
$ git clone https://github.com/pinecone-io/pinecone-ts-client
Cloning into 'pinecone-ts-client'...
remote: Enumerating objects: 319, done.
remote: Counting objects: 100% (319/319), done.
remote: Compressing objects: 100% (174/174), done.
remote: Total 319 (delta 177), reused 258 (delta 121), pack-reused 0
Receiving objects: 100% (319/319), 183.79 KiB | 794.00 KiB/s, done.
Resolving deltas: 100% (177/177), done.
$ cd pinecone-ts-client/
$ npm i

added 310 packages, and audited 312 packages in 1s

29 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

$ node --version
v18.15.0
$ npm --version
9.5.0
$ npm run build

> @pinecone-database/pinecone@0.0.10 build
> tsc

$ npm run test

> @pinecone-database/pinecone@0.0.10 test
> jest

  console.error
    Error waiting until collection is ready [Error: PineconeClient: Error calling describeCollection: collection fond-swift-collection not found]

      68 |     }
      69 |   } catch (e) {
    > 70 |     console.error('Error waiting until collection is ready', e)
         |             ^
      71 |   }
      72 | }
      73 |

      at utils/helpers.ts:70:13
      at step (utils/helpers.ts:33:23)
      at Object.throw (utils/helpers.ts:14:53)
      at rejected (utils/helpers.ts:6:65)

  console.error
    Error waiting until collection is ready [Error: PineconeClient: Error calling describeCollection: collection fond-swift-collection not found]

      68 |     }
      69 |   } catch (e) {
    > 70 |     console.error('Error waiting until collection is ready', e)
         |             ^
      71 |   }
      72 | }
      73 |

      at utils/helpers.ts:70:13
      at step (utils/helpers.ts:33:23)
      at Object.throw (utils/helpers.ts:14:53)
      at rejected (utils/helpers.ts:6:65)

  console.error
    Error waiting until collection is ready [Error: PineconeClient: Error calling describeCollection: collection fond-swift-collection not found]

      68 |     }
      69 |   } catch (e) {
    > 70 |     console.error('Error waiting until collection is ready', e)
         |             ^
      71 |   }
      72 | }
      73 |

      at utils/helpers.ts:70:13
      at step (utils/helpers.ts:33:23)
      at Object.throw (utils/helpers.ts:14:53)
      at rejected (utils/helpers.ts:6:65)

 FAIL  tests/index.test.ts (7.706 s)
  Pinecone Client Control Plane operations
    ✕ should create index (1828 ms)
    ✕ created index should be listed (1105 ms)
    ✕ should be able to describe and index  (83 ms)
    ✕ should be able to create a collection (163 ms)
    ✕ should be able to list collections (375 ms)
    ✕ should be able to describe collection (122 ms)
    ✕ should be able to delete a collection (120 ms)
    ✕ should be able to delete an index (186 ms)
  Pinecone Client Index Operations
    ✕ should create index (1146 ms)
    ✕ should be able to upsert a vector (344 ms)
    ✕ should be able to query a vector (188 ms)
    ✕ should be able to update a vector (182 ms)
    ✕ should be able to fetch vectors by ID (192 ms)
    ✕ should be able to delete a vector (179 ms)
    ✕ should be able to delete all vector in namespace (188 ms)

  ● Pinecone Client Control Plane operations › should create index
  ● Pinecone Client Control Plane operations › created index should be listed
  ● Pinecone Client Control Plane operations › should be able to describe and index 
  ● Pinecone Client Control Plane operations › should be able to create a collection
  ● Pinecone Client Control Plane operations › should be able to list collections
  ● Pinecone Client Control Plane operations › should be able to describe collection
  ● Pinecone Client Control Plane operations › should be able to delete a collection
  ● Pinecone Client Control Plane operations › should be able to delete an index
  ● Pinecone Client Index Operations › should create index
  ● Pinecone Client Index Operations › should be able to upsert a vector
  ● Pinecone Client Index Operations › should be able to query a vector
  ● Pinecone Client Index Operations › should be able to update a vector
  ● Pinecone Client Index Operations › should be able to fetch vectors by ID
  ● Pinecone Client Index Operations › should be able to delete a vector
  ● Pinecone Client Index Operations › should be able to delete all vector in namespace

Test Suites: 1 failed, 1 total
Tests:       15 failed, 15 total
Snapshots:   0 total
Time:        7.75 s, estimated 8 s
Ran all test suites.

Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  TLSWRAP

       99 |
      100 |     try {
    > 101 |       const response = await fetch(whoami, request)
          |                              ^
      102 |       const { project_name } = await response.json()
      103 |       return project_name
      104 |     } catch (error) {

      at PineconeClient.<anonymous> (src/index.ts:101:30)
      at step (src/index.ts:33:23)
      at Object.next (src/index.ts:14:53)
      at src/index.ts:8:71
      at Object.<anonymous>.__awaiter (src/index.ts:4:12)
      at PineconeClient.Object.<anonymous>.PineconeClient.getProjectName (src/index.ts:159:16)
      at PineconeClient.<anonymous> (src/index.ts:115:35)
      at step (src/index.ts:33:23)
      at Object.next (src/index.ts:14:53)
      at src/index.ts:8:71
      at Object.<anonymous>.__awaiter (src/index.ts:4:12)
      at PineconeClient.Object.<anonymous>.PineconeClient.init (src/index.ts:192:16)
      at tests/index.test.ts:40:18
      at step (tests/index.test.ts:33:23)
      at Object.next (tests/index.test.ts:14:53)
      at tests/index.test.ts:8:71
      at Object.<anonymous>.__awaiter (tests/index.test.ts:4:12)
      at Object.<anonymous> (tests/index.test.ts:35:13)
```

**Comment by rschwabco** [comment]
It seems like you're running into some sort of race condition. I'll investigate this. Thank you for reporting!

**Comment by rschwabco** [comment]
This was addressed in #27.

**Comment by sammyjava** [comment]
Current version tests continue to fail.

```
shokin@morangie:~/pinecone-ts-client$ git pull
Already up to date.
shokin@morangie:~/pinecone-ts-client$ git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
shokin@morangie:~/pinecone-ts-client$ npm run test

> @pinecone-database/pinecone@0.0.11 test
> jest --verbose=true

  console.error
    Error waiting until collection is ready [ErrorWithoutStackTrace: PineconeClient: Error calling describeCollection: collection disappointed-heron-collection not found]

      89 |     }
      90 |   } catch (e) {
    > 91 |     console.error('Error waiting until collection is ready', e)
         |             ^
      92 |   }
      93 | }
      94 |

      at utils/helpers.ts:91:13
      at step (utils/helpers.ts:44:23)
      at Object.throw (utils/helpers.ts:25:53)
      at rejected (utils/helpers.ts:17:65)

  console.error
    Error waiting until collection is ready [ErrorWithoutStackTrace: PineconeClient: Error calling describeCollection: collection disappointed-heron-collection not found]

      89 |     }
      90 |   } catch (e) {
    > 91 |     console.error('Error waiting until collection is ready', e)
         |             ^
      92 |   }
      93 | }
      94 |

      at utils/helpers.ts:91:13
      at step (utils/helpers.ts:44:23)
      at Object.throw (utils/helpers.ts:25:53)
      at rejected (utils/helpers.ts:17:65)

 FAIL  tests/index.test.ts (32.584 s)
  Pinecone Client Index Operations
    ✕ should create index (1627 ms)
    ✕ should be able to upsert a vector (375 ms)
    ✕ should be able to upsert a vector with sparse values (186 ms)
    ✕ should be able to query a vector (184 ms)
    ✕ should be able to query a vector with sparse values (181 ms)
    ✕ should be able to update a vector (10008 ms)
    ✕ should be able to fetch vectors by ID (1137 ms)
    ✕ should be able to delete a vector (10008 ms)
    ✕ should be able to delete all vector in namespace (741 ms)
  Pinecone Client Control Plane operations
    ✕ should create index (3177 ms)
    ✕ created index should be listed (1223 ms)
    ✕ should be able to describe and index  (76 ms)
    ✕ should be able to create a collection (118 ms)
    ✕ should be able to list collections (353 ms)
    ✕ should be able to describe collection (96 ms)
    ○ skipped should be able to delete a collection
    ○ skipped should be able to delete an index

  ● Pinecone Client Index Operations › should create index





  ● Pinecone Client Index Operations › should be able to upsert a vector





  ● Pinecone Client Index Operations › should be able to upsert a vector with sparse values





  ● Pinecone Client Index Operations › should be able to query a vector





  ● Pinecone Client Index Operations › should be able to query a vector with sparse values





  ● Pinecone Client Index Operations › should be able to update a vector





  ● Pinecone Client Index Operations › should be able to fetch vectors by ID





  ● Pinecone Client Index Operations › should be able to delete a vector





  ● Pinecone Client Index Operations › should be able to delete all vector in namespace





  ● Pinecone Client Control Plane operations › should create index





  ● Pinecone Client Control Plane operations › created index should be listed

    expect(received).toContain(expected) // indexOf

    Expected value: "disappointed-heron"
    Received array: ["pure-gas"]

      225 |   it('created index should be listed', async () => {
      226 |     const list = await client.listIndexes()
    > 227 |     expect(list).toContain(indexName)
          |                  ^
      228 |
      229 |   })
      230 |

      at tests/index.test.ts:227:18
      at step (tests/index.test.ts:33:23)
      at Object.next (tests/index.test.ts:14:53)
      at fulfilled (tests/index.test.ts:5:58)

  ● Pinecone Client Control Plane operations › should be able to describe and index 





  ● Pinecone Client Control Plane operations › should be able to create a collection





  ● Pinecone Client Control Plane operations › should be able to list collections

    expect(received).toContain(expected) // indexOf

    Expected value: "disappointed-heron-collection"
    Received array: []

      254 |     waitUntilCollectionIsReady(client, collectionName)
      255 |     const list = await client.listCollections()
    > 256 |     expect(list).toContain(collectionName)
          |                  ^
      257 |   })
      258 |
      259 |   it('should be able to describe collection', async () => {

      at tests/index.test.ts:256:18
      at step (tests/index.test.ts:33:23)
      at Object.next (tests/index.test.ts:14:53)
      at fulfilled (tests/index.test.ts:5:58)

  ● Pinecone Client Control Plane operations › should be able to describe collection





Test Suites: 1 failed, 1 total
Tests:       15 failed, 2 skipped, 17 total
Snapshots:   0 total
Time:        32.626 s
Ran all test suites.
```

**Comment by sammyjava** [comment]
Clean install of new version continues to fail tests.
```
shokin@morangie:~$ git clone https://github.com/pinecone-io/pinecone-ts-client
Cloning into 'pinecone-ts-client'...
remote: Enumerating objects: 380, done.
remote: Counting objects: 100% (380/380), done.
remote: Compressing objects: 100% (200/200), done.
remote: Total 380 (delta 212), reused 306 (delta 149), pack-reused 0
Receiving objects: 100% (380/380), 203.60 KiB | 28.00 KiB/s, done.
Resolving deltas: 100% (212/212), done.
shokin@morangie:~$ cd pinecone-ts-client/
shokin@morangie:~/pinecone-ts-client$ npm i

added 311 packages, and audited 313 packages in 1s

30 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
shokin@morangie:~/pinecone-ts-client$ npm run test

> @pinecone-database/pinecone@0.0.11 test
> jest --verbose=true

  console.error
    Error waiting until collection is ready [ErrorWithoutStackTrace: PineconeClient: Error calling describeCollection: collection potential-condor-collection not found]

      89 |     }
      90 |   } catch (e) {
    > 91 |     console.error('Error waiting until collection is ready', e)
         |             ^
      92 |   }
      93 | }
      94 |

      at utils/helpers.ts:91:13
      at step (utils/helpers.ts:44:23)
      at Object.throw (utils/helpers.ts:25:53)
      at rejected (utils/helpers.ts:17:65)

  console.error
    Error waiting until collection is ready [ErrorWithoutStackTrace: PineconeClient: Error calling describeCollection: collection potential-condor-collection not found]

      89 |     }
      90 |   } catch (e) {
    > 91 |     console.error('Error waiting until collection is ready', e)
         |             ^
      92 |   }
      93 | }
      94 |

      at utils/helpers.ts:91:13
      at step (utils/helpers.ts:44:23)
      at Object.throw (utils/helpers.ts:25:53)
      at rejected (utils/helpers.ts:17:65)

 FAIL  tests/index.test.ts (9.501 s)
  Pinecone Client Index Operations
    ✕ should create index (1559 ms)
    ✕ should be able to upsert a vector (390 ms)
    ✕ should be able to upsert a vector with sparse values (182 ms)
    ✕ should be able to query a vector (183 ms)
    ✕ should be able to query a vector with sparse values (180 ms)
    ✕ should be able to update a vector (185 ms)
    ✕ should be able to fetch vectors by ID (180 ms)
    ✕ should be able to delete a vector (286 ms)
    ✕ should be able to delete all vector in namespace (207 ms)
  Pinecone Client Control Plane operations
    ✕ should create index (1497 ms)
    ✕ created index should be listed (1441 ms)
    ✕ should be able to describe and index  (76 ms)
    ✕ should be able to create a collection (117 ms)
    ✕ should be able to list collections (280 ms)
    ✕ should be able to describe collection (92 ms)
    ○ skipped should be able to delete a collection
    ○ skipped should be able to delete an index

  ● Pinecone Client Index Operations › should create index





  ● Pinecone Client Index Operations › should be able to upsert a vector





  ● Pinecone Client Index Operations › should be able to upsert a vector with sparse values





  ● Pinecone Client Index Operations › should be able to query a vector





  ● Pinecone Client Index Operations › should be able to query a vector with sparse values





  ● Pinecone Client Index Operations › should be able to update a vector





  ● Pinecone Client Index Operations › should be able to fetch vectors by ID





  ● Pinecone Client Index Operations › should be able to delete a vector





  ● Pinecone Client Index Operations › should be able to delete all vector in namespace





  ● Pinecone Client Control Plane operations › should create index





  ● Pinecone Client Control Plane operations › created index should be listed

    expect(received).toContain(expected) // indexOf

    Expected value: "potential-condor"
    Received array: ["pure-gas"]

      225 |   it('created index should be listed', async () => {
      226 |     const list = await client.listIndexes()
    > 227 |     expect(list).toContain(indexName)
          |                  ^
      228 |
      229 |   })
      230 |

      at tests/index.test.ts:227:18
      at step (tests/index.test.ts:33:23)
      at Object.next (tests/index.test.ts:14:53)
      at fulfilled (tests/index.test.ts:5:58)

  ● Pinecone Client Control Plane operations › should be able to describe and index 





  ● Pinecone Client Control Plane operations › should be able to create a collection





  ● Pinecone Client Control Plane operations › should be able to list collections

    expect(received).toContain(expected) // indexOf

    Expected value: "potential-condor-collection"
    Received array: []

      254 |     waitUntilCollectionIsReady(client, collectionName)
      255 |     const list = await client.listCollections()
    > 256 |     expect(list).toContain(collectionName)
          |                  ^
      257 |   })
      258 |
      259 |   it('should be able to describe collection', async () => {

      at tests/index.test.ts:256:18
      at step (tests/index.test.ts:33:23)
      at Object.next (tests/index.test.ts:14:53)
      at fulfilled (tests/index.test.ts:5:58)

  ● Pinecone Client Control Plane operations › should be able to describe collection





Test Suites: 1 failed, 1 total
Tests:       15 failed, 2 skipped, 17 total
Snapshots:   0 total
Time:        9.541 s, estimated 11 s
Ran all test suites.
shokin@morangie:~/pinecone-ts-client$ 
```
