### ISSUE TITLE
ErrorWithoutStackTrace: PineconeClient: Error getting project name: TypeError: fetch failed

### ISSUE THREAD

**Issue by phrazzld** [pinecone-io/pinecone-ts-client#37]
I'm trying to integrate Pinecone with a NextJS + TypeScript project I'm working on.
- I've added my `PINECONE_API_KEY` to my `.env.local` file.
- I've run `yarn add @pinecone-database/pinecone`.
- I'm importing it in my new `pages/api/embeddings.ts` file like so:
`import { PineconeClient } from "@pinecone-database/pinecone"`
- I've defined the below initialization function:
```typescript
const initPinecone = async () => {
  console.log("Initializing Pinecone...");

  const pinecone = new PineconeClient();
  await pinecone.init({
    environment: process.env.NODE_ENV || "development",
    apiKey: process.env.PINECONE_API_KEY || "",
  });

  console.log("Pinecone initialized.");

  return pinecone;
};
```

But I never see the "Pinecone initialized." message in console output. Instead, I get the following error (absolute path to my current project directory abbreviated with "..."):
```
[ErrorWithoutStackTrace: PineconeClient: Error getting project name: TypeError: fetch failed]
Error: ErrorWithoutStackTrace: PineconeClient: Error getting project name: TypeError: fetch failed
    at addSourceToIndex (webpack-internal:///(api)/./pages/api/embeddings.ts:71:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async handlePost (webpack-internal:///(api)/./pages/api/embeddings.ts:79:17)
    at async Object.apiResolver (/.../node_modules/next/dist/server/api-utils/node.js:372:9)
    at async DevServer.runApi (/.../node_modules/next/dist/server/next-server.js:488:9)
    at async Object.fn (/.../node_modules/next/dist/server/next-server.js:751:37)
    at async Router.execute (/.../node_modules/next/dist/server/router.js:253:36)
    at async DevServer.run (/.../node_modules/next/dist/server/base-server.js:384:29)
    at async DevServer.run (/.../node_modules/next/dist/server/dev/next-dev-server.js:741:20)
    at async DevServer.handleRequest (/.../node_modules/next/dist/server/base-server.js:322:20)
```

Why is my Pinecone initialization failing?

**Comment by phrazzld** [comment]
*facepalm*

I misunderstood the `environment` parameter to pass to `init`. It's specified in the Pinecone dashboard:

![Screenshot 2023-04-02 at 19 41 05](https://user-images.githubusercontent.com/788415/229388467-bb0b1549-752a-4d54-98a5-00d43b25f256.png)
